name: Deploy MeetingPlanner to Azure

# on: [push]
on:
  push:
    branches:
      - development
      - master

env:
  AZURE_WEBAPP_NAME: MeetingPlanner
  AZURE_WEBAPP_PACKAGE_PATH: './MeetingPlanner'
  DOTNET_VERSION: '3.1.101'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      # Checkout the repository
      - uses: actions/checkout@development
      
      # Setup .NET Core SDK
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }} 
          
      # Run dotnet restore
      - name: Restore
        run: dotnet restore
      
      # Run dotnet build
      - name: Build
        run: dotnet build --no-restore -c Release
        
      # Run dotnet publish  
      - name: Publish
        run: dotnet publish --no-build -c Release -output ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
          
      # Deploy to Azure Web apps
      - name: 'Deploy to Azure WebApp'
        uses: azure/webapps-deploy@v2
        with: 
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE  }}
          package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}'